[package]
name = "file-trailer"
version = "0.1.0"
edition = "2018"

[lib]
name = "file_trailer"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logwatcher = "0.1.1"
tokio = { version = "1.11.0", features = ["full"] }
log = "0.4.14"
env_logger = "0.9.0"
async-trait = "0.1.51"
chrono = "0.4.19"